version: '3.0'

services:
  valhalla:
    build:
      context: ./
      dockerfile: Dockerfile.valhalla
    ports:
      - 8002:8002
    volumes:
      - ./config:/conf
      - ./tiles:/data
  processing:
    build:
      context: ./
      dockerfile: Dockerfile.processing
    ports:
      - 4444:8888
    depends_on:
      - valhalla
    volumes:
      - ./:/home/jovyan
    command: python process_od_matrix.py
